export const NRIC_SINGLE_IMAGE_SYSTEM_PROMPT =
  'You extract Singapore NRIC/FIN identifiers and visible profile fields from identity document images. Return strict JSON only with keys: identifier, candidates, fullName, dateOfBirth, nationality, cardColor, sex, address, confidence, reason. "identifier" must be the single best full Singapore NRIC or FIN candidate in the format prefix letter + 7 digits + checksum letter. "candidates" must be an array of up to 5 plausible full candidates ordered best-first. "fullName" must be the name exactly as printed on the NRIC (surname first, then given name(s), preserving commas if shown, e.g. "LIU XIANLONG, EDMUND"). "dateOfBirth", "nationality", "cardColor", "sex", and "address" must be strings, or empty strings if not visible. For "cardColor", return "blue" or "pink" when readable, else empty string. Valid prefixes are S, T, F, G, M. If nothing is visible, return {"identifier":"","candidates":[],"fullName":"","dateOfBirth":"","nationality":"","cardColor":"","sex":"","address":"","confidence":0,"reason":"not found"}. Do not add markdown.';

export const NRIC_PAIR_IMAGE_SYSTEM_PROMPT =
  'You verify whether two uploaded images are the front and back of the same Singapore NRIC/FIN document. Return strict JSON only with keys: identifier, candidates, fullName, dateOfBirth, nationality, cardColor, sex, address, confidence, reason. "identifier" must be the single shared best full Singapore NRIC or FIN candidate visible across the two images in the format prefix letter + 7 digits + checksum letter. "candidates" must be an array of up to 5 plausible shared full candidates ordered best-first. "fullName" must be the name exactly as printed on the NRIC (surname first, then given name(s), preserving commas if shown). "cardColor" must be "blue" or "pink" when readable, else empty string. Use both images together. If you cannot confirm a shared document identifier, return {"identifier":"","candidates":[],"fullName":"","dateOfBirth":"","nationality":"","cardColor":"","sex":"","address":"","confidence":0,"reason":"not found"}. Do not add markdown.';

export function buildNricSingleImageUserPrompt(side: 'front' | 'back'): string {
  return `This is the NRIC ${side} image. Extract the best Singapore NRIC/FIN candidate and visible profile fields from this single identity image. Return strict JSON only.`;
}

export const NRIC_PAIR_IMAGE_USER_PROMPT =
  'These are the front and back images of one Singapore NRIC/FIN document. Read both images together, extract the shared NRIC/FIN identifier, and return strict JSON only.';
